### ISSUE TITLE
Function sentiment.ai_install() not available

### ISSUE THREAD

**Issue by jfsavardenap** [BenWiseman/sentiment.ai#11]
Hello,
   I installed your package sentiment.ai from CRAN. When I try to use the fonction sentiment.ai_install() for the first time I get the following error:
Error in sentiment.ai_install() : 
  could not find function "sentiment.ai_install"

I tried with both RStudio and R base GUI.

I use R version 4.1.3 with RStudio 2021.09.2 Build 382 on a Mac M1.

Do you have an idea on what the problem could be?

**Comment by iamdavecampbell** [comment]
Looks like it should be:
init_sentiment.ai() but the error message and the readme both point to sentiment.ai_install()

**Comment by BenWiseman** [comment]
Was corrected in docs

**Comment by iamdavecampbell** [comment]
I see now that it shows up in:
sentiment.ai/rpackage/sentiment.ai/R/init_and_install.R  

On line 521:
         "run **sentiment.ai_install**() on envname '", envname, "' first.",

It should be:

         "run **install_sentiment.ai**() on envname '", envname, "' first.",
